<a href="https://colab.research.google.com/github/ryukkt62/ryukkt62/blob/main/RNN%EB%AA%A8%EB%8D%B8%EC%A0%95%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. MLP DNN 모델(다:1)

In [1]:
# 1. 데이터
import numpy as np
dataset = np.array([1,2,3,4,5,6,7,8,9,10])
print(dataset)


# time_steps는 x의 row를 몇개씩 넣을건지
def split_xy1(dataset, time_steps):
    x, y = list(), list()
    for i in range(len(dataset)):
        end_number = i + time_steps
        if end_number > len(dataset)-1:
            break
        tmp_x = dataset[i:end_number]
        tmp_y = dataset[end_number]

        x.append(tmp_x)
        y.append(tmp_y)

    return np.array(x), np.array(y)
x, y = split_xy1(dataset,4)
print('x',"\n",x, "\n", 'y', "\n",y)
print("x.shape: ", x.shape)
print("y.shape: ", y.shape)

[ 1  2  3  4  5  6  7  8  9 10]
x 
 [[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]] 
 y 
 [ 5  6  7  8  9 10]
x.shape:  (6, 4)
y.shape:  (6,)


In [2]:
from keras.models import Sequential
from keras.layers import Dense

# 2. 모델 구성
model = Sequential()
model.add(Dense(64, input_shape=(4,)))
# model.add(Dense(64, input_dim=4))
model.add(Dense(1))

# 3. 훈련
model.compile(optimizer='adam',loss='mse')
model.fit(x, y, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 446ms/step - loss: 62.9145
Epoch 2/1000
1/1 [==============================] - 0s 7ms/step - loss: 57.7778
Epoch 3/1000
1/1 [==============================] - 0s 6ms/step - loss: 52.8693
Epoch 4/1000
1/1 [==============================] - 0s 6ms/step - loss: 48.1923
Epoch 5/1000
1/1 [==============================] - 0s 8ms/step - loss: 43.7495
Epoch 6/1000
1/1 [==============================] - 0s 7ms/step - loss: 39.5429
Epoch 7/1000
1/1 [==============================] - 0s 6ms/step - loss: 35.5734
Epoch 8/1000
1/1 [==============================] - 0s 5ms/step - loss: 31.8417
Epoch 9/1000
1/1 [==============================] - 0s 6ms/step - loss: 28.3476
Epoch 10/1000
1/1 [==============================] - 0s 4ms/step - loss: 25.0902
Epoch 11/1000
1/1 [==============================] - 0s 4ms/step - loss: 22.0675
Epoch 12/1000
1/1 [==============================] - 0s 8ms/step - loss: 19.2770
Epoch 13/1000
1/1 [================

In [3]:
# 4. 평가, 예측
mse = model.evaluate(x, y)
print("mse: ", mse)

x_pred = np.array([7,8,9,10])
x_pred = x_pred.reshape(1, x_pred.shape[0])
print(x_pred)
print(x_pred.shape)

y_pred = model.predict(x_pred)
print(y_pred)

1/1 [==============================] - 0s 294ms/step - loss: 1.6553e-04
mse:  0.00016553491877857596
[[ 7  8  9 10]]
(1, 4)
1/1 [==============================] - 0s 197ms/step
[[11.021133]]


# 2. MLP RNN 모델(다:1)

In [4]:
# 1. 데이터
import numpy as np
dataset = np.array([1,2,3,4,5,6,7,8,9,10])
print(dataset)


# time_steps는 x의 row를 몇개씩 넣을건지
def split_xy1(dataset, time_steps):
    x, y = list(), list()
    for i in range(len(dataset)):
        end_number = i + time_steps
        if end_number > len(dataset)-1:
            break
        tmp_x = dataset[i:end_number]
        tmp_y = dataset[end_number]

        x.append(tmp_x)
        y.append(tmp_y)

    return np.array(x), np.array(y)
x, y = split_xy1(dataset,4)
print('x',"\n",x, "\n", 'y', "\n",y)
print("x.shape: ", x.shape)
print("y.shape: ", y.shape)

[ 1  2  3  4  5  6  7  8  9 10]
x 
 [[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]] 
 y 
 [ 5  6  7  8  9 10]
x.shape:  (6, 4)
y.shape:  (6,)


In [5]:
# RNN은 데이터는 3차원, input은 2차원이어야함
# x를 3차원으로 바꿔줌
# y는 그대로 둬도 괜찮음
# 원래는 (면,행,열)인데 keras api상으로 마지막이 열이 아니라 feature임
# keras api는 일반적인 array형식과 조금 다름 주의하기.

x = x.reshape(x.shape[0],x.shape[1],1)
print(x.shape)

(6, 4, 1)


In [6]:
from keras.models import Sequential
from keras.layers import Dense, LSTM

# 2. 모델 구성
model = Sequential()
model.add(LSTM(64, input_shape=(4,1)))
model.add(Dense(1)) # y가 (6,)이므로 Dense(1)

# 3. 훈련
model.compile(optimizer='adam',loss='mse')
model.fit(x, y, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 4s 4s/step - loss: 59.7264
Epoch 2/1000
1/1 [==============================] - 0s 12ms/step - loss: 58.2861
Epoch 3/1000
1/1 [==============================] - 0s 15ms/step - loss: 56.8631
Epoch 4/1000
1/1 [==============================] - 0s 14ms/step - loss: 55.4551
Epoch 5/1000
1/1 [==============================] - 0s 8ms/step - loss: 54.0602
Epoch 6/1000
1/1 [==============================] - 0s 7ms/step - loss: 52.6765
Epoch 7/1000
1/1 [==============================] - 0s 12ms/step - loss: 51.3029
Epoch 8/1000
1/1 [==============================] - 0s 12ms/step - loss: 49.9380
Epoch 9/1000
1/1 [==============================] - 0s 7ms/step - loss: 48.5806
Epoch 10/1000
1/1 [==============================] - 0s 7ms/step - loss: 47.2293
Epoch 11/1000
1/1 [==============================] - 0s 7ms/step - loss: 45.8831
Epoch 12/1000
1/1 [==============================] - 0s 7ms/step - loss: 44.5410
Epoch 13/1000
1/1 [==============

In [7]:
# 4. 평가, 예측
mse = model.evaluate(x, y)
print("mse: ", mse)

x_pred = np.array([7,8,9,10])
x_pred = x_pred.reshape(1, x_pred.shape[0], 1)
print(x_pred)
print(x_pred.shape)

y_pred = model.predict(x_pred)
print(y_pred)

1/1 [==============================] - 0s 473ms/step - loss: 0.0013
mse:  0.0012794927461072803
[[[ 7]
  [ 8]
  [ 9]
  [10]]]
(1, 4, 1)
1/1 [==============================] - 0s 432ms/step
[[10.61037]]


# 3. MLP RNN 모델(다:다)



In [8]:
# 1. 데이터
import numpy as np
dataset = np.array([1,2,3,4,5,6,7,8,9,10])
print(dataset)


# time_steps는 x의 row를 몇개씩 넣을건지
# y_columns는 y의 row를 몇개씩 넣을건지
def split_xy2(dataset, time_steps, y_columns):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_columns
        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i : x_end_number]
        tmp_y = dataset[x_end_number : y_end_number]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

time_steps = 4
y_column = 2
x, y = split_xy2(dataset, time_steps, y_column)
print('x',"\n",x, "\n", 'y',"\n",y)
print("x.shape: ", x.shape)
print("y.shape: ", y.shape)

[ 1  2  3  4  5  6  7  8  9 10]
x 
 [[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]] 
 y 
 [[ 5  6]
 [ 6  7]
 [ 7  8]
 [ 8  9]
 [ 9 10]]
x.shape:  (5, 4)
y.shape:  (5, 2)


In [9]:
# RNN은 데이터는 3차원, input은 2차원이어야함
# x를 3차원으로 바꿔줌
# y는 그대로 둬도 괜찮음
# 원래는 (면,행,열)인데 keras api상으로 마지막이 열이 아니라 feature임

x = x.reshape(x.shape[0],x.shape[1],1)
print(x.shape)

(5, 4, 1)


In [10]:
from keras.models import Sequential
from keras.layers import Dense, LSTM

# 2. 모델 구성
model = Sequential()
model.add(LSTM(64, input_shape=(4,1)))
model.add(Dense(2)) # y가 (5,2)이므로 Dense(2)

# 3. 훈련
model.compile(optimizer='adam',loss='mse')
model.fit(x, y, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 2s 2s/step - loss: 54.9152
Epoch 2/1000
1/1 [==============================] - 0s 11ms/step - loss: 53.9080
Epoch 3/1000
1/1 [==============================] - 0s 7ms/step - loss: 52.9030
Epoch 4/1000
1/1 [==============================] - 0s 7ms/step - loss: 51.8988
Epoch 5/1000
1/1 [==============================] - 0s 8ms/step - loss: 50.8943
Epoch 6/1000
1/1 [==============================] - 0s 8ms/step - loss: 49.8882
Epoch 7/1000
1/1 [==============================] - 0s 8ms/step - loss: 48.8791
Epoch 8/1000
1/1 [==============================] - 0s 9ms/step - loss: 47.8664
Epoch 9/1000
1/1 [==============================] - 0s 6ms/step - loss: 46.8492
Epoch 10/1000
1/1 [==============================] - 0s 9ms/step - loss: 45.8269
Epoch 11/1000
1/1 [==============================] - 0s 6ms/step - loss: 44.7989
Epoch 12/1000
1/1 [==============================] - 0s 8ms/step - loss: 43.7646
Epoch 13/1000
1/1 [==================

In [11]:
# 4. 평가, 예측
mse = model.evaluate(x, y)
print("mse: ", mse)

x_pred = np.array([7,8,9,10])
x_pred = x_pred.reshape(1, x_pred.shape[0], 1)
print(x_pred)
print(x_pred.shape)

y_pred = model.predict(x_pred)
print(y_pred)

1/1 [==============================] - 1s 545ms/step - loss: 0.0012
mse:  0.0012217467883601785
[[[ 7]
  [ 8]
  [ 9]
  [10]]]
(1, 4, 1)
1/1 [==============================] - 0s 450ms/step
[[ 9.976069 10.888113]]


# 4. MLP RNN 모델(다입력 다:1)



In [12]:
# 1. 데이터
import numpy as np
dataset = np.array([[1,2,3,4,5,6,7,8,9,10],
 [11,12,13,14,15,16,17,18,19,20],
  [21,22,23,24,25,26,27,28,29,30]])

print("dataset.shape: ", dataset.shape)
dataset = np.transpose(dataset)
print(dataset)
print("dataset.shape: ", dataset.shape)

dataset.shape:  (3, 10)
[[ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]
 [10 20 30]]
dataset.shape:  (10, 3)


In [13]:
# time_steps는 x의 row를 몇개씩 넣을건지
# y_columns는 y의 row를 몇개씩 넣을건지
def split_xy3(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column -1

        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i:x_end_number, :-1]
        tmp_y = dataset[x_end_number-1:y_end_number, -1]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

time_steps = 3
y_column = 1
x, y = split_xy3(dataset, time_steps, y_column)
print('x',"\n",x, "\n", 'y',"\n",y)
print("x.shape: ", x.shape)
print("y.shape: ", y.shape)

x 
 [[[ 1 11]
  [ 2 12]
  [ 3 13]]

 [[ 2 12]
  [ 3 13]
  [ 4 14]]

 [[ 3 13]
  [ 4 14]
  [ 5 15]]

 [[ 4 14]
  [ 5 15]
  [ 6 16]]

 [[ 5 15]
  [ 6 16]
  [ 7 17]]

 [[ 6 16]
  [ 7 17]
  [ 8 18]]

 [[ 7 17]
  [ 8 18]
  [ 9 19]]

 [[ 8 18]
  [ 9 19]
  [10 20]]] 
 y 
 [[23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]]
x.shape:  (8, 3, 2)
y.shape:  (8, 1)


In [14]:
# RNN은 데이터는 3차원, input은 2차원이어야함
# y는 그대로 둬도 괜찮음
# 모델의 output에 사용할 수 있게 y값을 벡터 형태로 변경
# 원래는 (면,행,열)인데 keras api상으로 마지막이 열이 아니라 feature임

y = y.reshape(y.shape[0])
print(y.shape)

(8,)


In [15]:
from keras.models import Sequential
from keras.layers import Dense, LSTM

# 2. 모델 구성
model = Sequential()
model.add(LSTM(64, input_shape=(3,2)))
model.add(Dense(1)) # y가 (8,)이므로 Dense(1)

# 3. 훈련
model.compile(optimizer='adam',loss='mse')
model.fit(x, y, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 2s 2s/step - loss: 684.0957
Epoch 2/1000
1/1 [==============================] - 0s 8ms/step - loss: 678.4296
Epoch 3/1000
1/1 [==============================] - 0s 8ms/step - loss: 672.8124
Epoch 4/1000
1/1 [==============================] - 0s 6ms/step - loss: 667.2457
Epoch 5/1000
1/1 [==============================] - 0s 7ms/step - loss: 661.7306
Epoch 6/1000
1/1 [==============================] - 0s 6ms/step - loss: 656.2664
Epoch 7/1000
1/1 [==============================] - 0s 8ms/step - loss: 650.8514
Epoch 8/1000
1/1 [==============================] - 0s 7ms/step - loss: 645.4836
Epoch 9/1000
1/1 [==============================] - 0s 4ms/step - loss: 640.1602
Epoch 10/1000
1/1 [==============================] - 0s 6ms/step - loss: 634.8777
Epoch 11/1000
1/1 [==============================] - 0s 5ms/step - loss: 629.6324
Epoch 12/1000
1/1 [==============================] - 0s 5ms/step - loss: 624.4205
Epoch 13/1000
1/1 [=======

In [16]:
# 4. 평가, 예측
mse = model.evaluate(x, y)
print("mse: ", mse)

x_pred = np.array([[9,10,11],[19,20,21]])
x_pred = np.transpose(x_pred)
x_pred = x_pred.reshape(1, x_pred.shape[0], x_pred.shape[1])
print(x_pred)
print(x_pred.shape)

y_pred = model.predict(x_pred,batch_size=1)
print(y_pred)

1/1 [==============================] - 1s 585ms/step - loss: 0.1758
mse:  0.1758168786764145
[[[ 9 19]
  [10 20]
  [11 21]]]
(1, 3, 2)
1/1 [==============================] - 1s 525ms/step
[[28.88809]]


* ## _1행을 연산할 때 우리가 이 모델을 처음에 만들었던 방식으로는 1,2,3이 연산한 것과 11,12,13이 연산한 것을 계산해서 23이 나오는 형태였는데, 자르고 나서 보면 1,11,2,12,3,13이 연산되어 23이 나옴. 즉 얼핏보기에는 연속적인 데이터라고 볼 수 있으나 자세히 보면 연속적인 데이터가 아님_

# 5. MLP DNN 모델(다입력 다:1)

In [17]:
# 1. 데이터
import numpy as np
dataset = np.array([[1,2,3,4,5,6,7,8,9,10],
 [11,12,13,14,15,16,17,18,19,20],
  [21,22,23,24,25,26,27,28,29,30]])

print("dataset.shape: ", dataset.shape)
dataset = np.transpose(dataset)
print(dataset)
print("dataset.shape: ", dataset.shape)

dataset.shape:  (3, 10)
[[ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]
 [10 20 30]]
dataset.shape:  (10, 3)


In [18]:
# time_steps는 x의 row를 몇개씩 넣을건지
# y_columns는 y의 row를 몇개씩 넣을건지
def split_xy3(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column -1

        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i:x_end_number, :-1]
        tmp_y = dataset[x_end_number-1:y_end_number, -1]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

time_steps = 3
y_column = 1
x, y = split_xy3(dataset, time_steps, y_column)
print('x',"\n",x, "\n", 'y',"\n",y)
print("x.shape: ", x.shape)
print("y.shape: ", y.shape)

x 
 [[[ 1 11]
  [ 2 12]
  [ 3 13]]

 [[ 2 12]
  [ 3 13]
  [ 4 14]]

 [[ 3 13]
  [ 4 14]
  [ 5 15]]

 [[ 4 14]
  [ 5 15]
  [ 6 16]]

 [[ 5 15]
  [ 6 16]
  [ 7 17]]

 [[ 6 16]
  [ 7 17]
  [ 8 18]]

 [[ 7 17]
  [ 8 18]
  [ 9 19]]

 [[ 8 18]
  [ 9 19]
  [10 20]]] 
 y 
 [[23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]]
x.shape:  (8, 3, 2)
y.shape:  (8, 1)


In [19]:
x = x.reshape(x.shape[0], x.shape[1] * x.shape[2])
print(x.shape)

(8, 6)


In [20]:
# 2. 모델 구성
from keras.models import Sequential
from keras.layers import Dense, LSTM

model = Sequential()
# model.add(LSTM(64, input_shape=(3,2)))
model.add(Dense(64, input_shape=(6,)))
model.add(Dense(1))

# 3. 훈련
model.compile(optimizer='adam',loss='mse')
model.fit(x, y, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 1s 501ms/step - loss: 354.6801
Epoch 2/1000
1/1 [==============================] - 0s 10ms/step - loss: 324.1960
Epoch 3/1000
1/1 [==============================] - 0s 10ms/step - loss: 295.1333
Epoch 4/1000
1/1 [==============================] - 0s 7ms/step - loss: 267.5173
Epoch 5/1000
1/1 [==============================] - 0s 10ms/step - loss: 241.3687
Epoch 6/1000
1/1 [==============================] - 0s 5ms/step - loss: 216.7020
Epoch 7/1000
1/1 [==============================] - 0s 8ms/step - loss: 193.5271
Epoch 8/1000
1/1 [==============================] - 0s 9ms/step - loss: 171.8494
Epoch 9/1000
1/1 [==============================] - 0s 5ms/step - loss: 151.6694
Epoch 10/1000
1/1 [==============================] - 0s 6ms/step - loss: 132.9832
Epoch 11/1000
1/1 [==============================] - 0s 7ms/step - loss: 115.7810
Epoch 12/1000
1/1 [==============================] - 0s 5ms/step - loss: 100.0478
Epoch 13/1000
1/1 [=

In [21]:
# 4. 평가, 예측
mse = model.evaluate(x, y)
print("mse: ", mse)

x_pred = np.array([[9,10,11],[19,20,21]])
x_pred = x_pred.reshape(1, x_pred.shape[0] * x_pred.shape[1])
print(x_pred)
print(x_pred.shape)
y_pred = model.predict(x_pred,batch_size=1)
print(y_pred)

1/1 [==============================] - 0s 199ms/step - loss: 2.2230e-07


mse:  2.2230460672290064e-07
[[ 9 10 11 19 20 21]]
(1, 6)
1/1 [==============================] - 0s 50ms/step
[[21.589746]]


# 6. MLP RNN 모델(다입력 다:다)

In [22]:
# 1. 데이터
import numpy as np
dataset = np.array([[1,2,3,4,5,6,7,8,9,10],
 [11,12,13,14,15,16,17,18,19,20],
  [21,22,23,24,25,26,27,28,29,30]])

print("dataset.shape: ", dataset.shape)
dataset = np.transpose(dataset)
print(dataset)
print("dataset.shape: ", dataset.shape)

dataset.shape:  (3, 10)
[[ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]
 [10 20 30]]
dataset.shape:  (10, 3)


In [23]:
# time_steps는 x의 row를 몇개씩 넣을건지
# y_columns는 y의 row를 몇개씩 넣을건지
def split_xy3(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column -1

        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i:x_end_number, :-1]
        tmp_y = dataset[x_end_number-1:y_end_number, -1]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

time_steps = 3
y_column = 2
x, y = split_xy3(dataset, time_steps, y_column)
print('x',"\n",x, "\n", 'y',"\n",y)
print("x.shape: ", x.shape)
print("y.shape: ", y.shape)

x 
 [[[ 1 11]
  [ 2 12]
  [ 3 13]]

 [[ 2 12]
  [ 3 13]
  [ 4 14]]

 [[ 3 13]
  [ 4 14]
  [ 5 15]]

 [[ 4 14]
  [ 5 15]
  [ 6 16]]

 [[ 5 15]
  [ 6 16]
  [ 7 17]]

 [[ 6 16]
  [ 7 17]
  [ 8 18]]

 [[ 7 17]
  [ 8 18]
  [ 9 19]]] 
 y 
 [[23 24]
 [24 25]
 [25 26]
 [26 27]
 [27 28]
 [28 29]
 [29 30]]
x.shape:  (7, 3, 2)
y.shape:  (7, 2)


In [24]:
# 2. 모델 구성
from keras.models import Sequential
from keras.layers import Dense, LSTM

model = Sequential()
model.add(LSTM(64, input_shape=(3,2)))
model.add(Dense(2))

# 3. 훈련
model.compile(optimizer='adam',loss='mse')
model.fit(x, y, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 2s 2s/step - loss: 675.5049
Epoch 2/1000
1/1 [==============================] - 0s 6ms/step - loss: 671.4044
Epoch 3/1000
1/1 [==============================] - 0s 13ms/step - loss: 667.2941
Epoch 4/1000
1/1 [==============================] - 0s 7ms/step - loss: 663.1734
Epoch 5/1000
1/1 [==============================] - 0s 12ms/step - loss: 659.0407
Epoch 6/1000
1/1 [==============================] - 0s 5ms/step - loss: 654.8942
Epoch 7/1000
1/1 [==============================] - 0s 6ms/step - loss: 650.7311
Epoch 8/1000
1/1 [==============================] - 0s 7ms/step - loss: 646.5472
Epoch 9/1000
1/1 [==============================] - 0s 6ms/step - loss: 642.3367
Epoch 10/1000
1/1 [==============================] - 0s 6ms/step - loss: 638.0923
Epoch 11/1000
1/1 [==============================] - 0s 8ms/step - loss: 633.8065
Epoch 12/1000
1/1 [==============================] - 0s 8ms/step - loss: 629.4716
Epoch 13/1000
1/1 [=====

In [25]:
# 4. 평가, 예측
mse = model.evaluate(x, y)
print("mse: ", mse)

x_pred = np.array([[9,10,11],[19,20,21]])
x_pred = np.transpose(x_pred)
x_pred = x_pred.reshape(1, x_pred.shape[0], x_pred.shape[1])
print(x_pred)
print(x_pred.shape)
y_pred = model.predict(x_pred,batch_size=1)
print(y_pred)

1/1 [==============================] - 1s 507ms/step - loss: 1.7353
mse:  1.735320806503296
[[[ 9 19]
  [10 20]
  [11 21]]]
(1, 3, 2)


1/1 [==============================] - 0s 433ms/step
[[26.484163 27.57952 ]]


# 7. MLP DNN 모델(다입력 다:다)

In [26]:
# 1. 데이터
import numpy as np
dataset = np.array([[1,2,3,4,5,6,7,8,9,10],
 [11,12,13,14,15,16,17,18,19,20],
  [21,22,23,24,25,26,27,28,29,30]])

print("dataset.shape: ", dataset.shape)
dataset = np.transpose(dataset)
print(dataset)
print("dataset.shape: ", dataset.shape)

dataset.shape:  (3, 10)
[[ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]
 [10 20 30]]
dataset.shape:  (10, 3)


In [27]:
# time_steps는 x의 row를 몇개씩 넣을건지
# y_columns는 y의 row를 몇개씩 넣을건지
def split_xy3(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column -1

        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i:x_end_number, :-1]
        tmp_y = dataset[x_end_number-1:y_end_number, -1]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

time_steps = 3
y_column = 2
x, y = split_xy3(dataset, time_steps, y_column)
print('x',"\n",x, "\n", 'y',"\n",y)
print("x.shape: ", x.shape)
print("y.shape: ", y.shape)

x 
 [[[ 1 11]
  [ 2 12]
  [ 3 13]]

 [[ 2 12]
  [ 3 13]
  [ 4 14]]

 [[ 3 13]
  [ 4 14]
  [ 5 15]]

 [[ 4 14]
  [ 5 15]
  [ 6 16]]

 [[ 5 15]
  [ 6 16]
  [ 7 17]]

 [[ 6 16]
  [ 7 17]
  [ 8 18]]

 [[ 7 17]
  [ 8 18]
  [ 9 19]]] 
 y 
 [[23 24]
 [24 25]
 [25 26]
 [26 27]
 [27 28]
 [28 29]
 [29 30]]
x.shape:  (7, 3, 2)
y.shape:  (7, 2)


In [28]:
x = x.reshape(x.shape[0], x.shape[1] * x.shape[2])
print(x.shape)

(7, 6)


In [29]:
# 2. 모델 구성
from keras.models import Sequential
from keras.layers import Dense, LSTM

model = Sequential()
model.add(Dense(64, input_shape=(6,)))
model.add(Dense(2))

# 3. 훈련
model.compile(optimizer='adam',loss='mse')
model.fit(x, y, epochs=300)

Epoch 1/300
1/1 [==============================] - 1s 623ms/step - loss: 875.8564
Epoch 2/300
1/1 [==============================] - 0s 7ms/step - loss: 836.9101
Epoch 3/300
1/1 [==============================] - 0s 8ms/step - loss: 798.9174
Epoch 4/300
1/1 [==============================] - 0s 9ms/step - loss: 761.8851
Epoch 5/300
1/1 [==============================] - 0s 9ms/step - loss: 725.8199
Epoch 6/300
1/1 [==============================] - 0s 9ms/step - loss: 690.7255
Epoch 7/300
1/1 [==============================] - 0s 8ms/step - loss: 656.6056
Epoch 8/300
1/1 [==============================] - 0s 6ms/step - loss: 623.4634
Epoch 9/300
1/1 [==============================] - 0s 7ms/step - loss: 591.2999
Epoch 10/300
1/1 [==============================] - 0s 8ms/step - loss: 560.1154
Epoch 11/300
1/1 [==============================] - 0s 6ms/step - loss: 529.9091
Epoch 12/300
1/1 [==============================] - 0s 6ms/step - loss: 500.6794
Epoch 13/300
1/1 [=================

In [30]:
# 4. 평가, 예측
mse = model.evaluate(x, y)
print("mse: ", mse)

x_pred = np.array([[9,10,11],[19,20,21]])
x_pred = np.transpose(x_pred)
x_pred = x_pred.reshape(1, x_pred.shape[0]*x_pred.shape[1])
print(x_pred)
print(x_pred.shape)
y_pred = model.predict(x_pred,batch_size=1)
print(y_pred)

1/1 [==============================] - 0s 116ms/step - loss: 3.3378
mse:  3.337846517562866
[[ 9 19 10 20 11 21]]
(1, 6)
1/1 [==============================] - 0s 87ms/step
[[35.767605 35.468815]]


# 8. RNN 모델(다입력 다:다 두번째)

In [31]:
# 1. 데이터
import numpy as np
dataset = np.array([[1,2,3,4,5,6,7,8,9,10],
 [11,12,13,14,15,16,17,18,19,20],
  [21,22,23,24,25,26,27,28,29,30]])

print("dataset.shape: ", dataset.shape)
dataset = np.transpose(dataset)
print(dataset)
print("dataset.shape: ", dataset.shape)

dataset.shape:  (3, 10)
[[ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]
 [10 20 30]]
dataset.shape:  (10, 3)


In [32]:
def split_xy5(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i+time_steps
        y_end_number = x_end_number + y_column

        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i:x_end_number, :]
        tmp_y = dataset[x_end_number:y_end_number,:]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

time_steps = 3
y_column = 1
x, y = split_xy5(dataset, time_steps, y_column)
print('x',"\n",x, "\n", 'y',"\n",y)
print("x.shape: ", x.shape)
print("y.shape: ", y.shape)

x 
 [[[ 1 11 21]
  [ 2 12 22]
  [ 3 13 23]]

 [[ 2 12 22]
  [ 3 13 23]
  [ 4 14 24]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]

 [[ 4 14 24]
  [ 5 15 25]
  [ 6 16 26]]

 [[ 5 15 25]
  [ 6 16 26]
  [ 7 17 27]]

 [[ 6 16 26]
  [ 7 17 27]
  [ 8 18 28]]

 [[ 7 17 27]
  [ 8 18 28]
  [ 9 19 29]]] 
 y 
 [[[ 4 14 24]]

 [[ 5 15 25]]

 [[ 6 16 26]]

 [[ 7 17 27]]

 [[ 8 18 28]]

 [[ 9 19 29]]

 [[10 20 30]]]
x.shape:  (7, 3, 3)
y.shape:  (7, 1, 3)


In [33]:
y = y.reshape(y.shape[0],y.shape[2])
print(y.shape)

(7, 3)


In [34]:
# 2. 모델 구성
from keras.models import Sequential
from keras.layers import Dense, LSTM

model = Sequential()
model.add(LSTM(64, input_shape=(3,3)))
model.add(Dense(3))

# 3. 훈련
model.compile(optimizer='adam',loss='mse')
model.fit(x, y, epochs=300)

Epoch 1/300
1/1 [==============================] - 3s 3s/step - loss: 351.6648
Epoch 2/300
1/1 [==============================] - 0s 9ms/step - loss: 348.2319
Epoch 3/300
1/1 [==============================] - 0s 12ms/step - loss: 344.8328
Epoch 4/300
1/1 [==============================] - 0s 9ms/step - loss: 341.4888
Epoch 5/300
1/1 [==============================] - 0s 10ms/step - loss: 338.2138
Epoch 6/300
1/1 [==============================] - 0s 9ms/step - loss: 335.0105
Epoch 7/300
1/1 [==============================] - 0s 9ms/step - loss: 331.8742
Epoch 8/300
1/1 [==============================] - 0s 7ms/step - loss: 328.7952
Epoch 9/300
1/1 [==============================] - 0s 7ms/step - loss: 325.7624
Epoch 10/300
1/1 [==============================] - 0s 9ms/step - loss: 322.7650
Epoch 11/300
1/1 [==============================] - 0s 10ms/step - loss: 319.7935
Epoch 12/300
1/1 [==============================] - 0s 9ms/step - loss: 316.8402
Epoch 13/300
1/1 [=================

In [35]:
# 4. 평가, 예측
mse = model.evaluate(x, y)
print("mse: ", mse)

x_pred = np.array([[8,9,10],[18,19,20],[28,29,30]])
x_pred = np.transpose(x_pred)
x_pred = x_pred.reshape(1, x_pred.shape[0],x_pred.shape[1])
print(x_pred)
print(x_pred.shape)
y_pred = model.predict(x_pred,batch_size=1)
print(y_pred)

1/1 [==============================] - 0s 418ms/step - loss: 10.3854
mse:  10.385360717773438
[[[ 8 18 28]
  [ 9 19 29]
  [10 20 30]]]
(1, 3, 3)
1/1 [==============================] - 0s 389ms/step
[[ 7.0093875 16.404726  22.677921 ]]


# 9. DNN 모델(다입력 다:다 두번째)

In [36]:
# 1. 데이터
import numpy as np
dataset = np.array([[1,2,3,4,5,6,7,8,9,10],
 [11,12,13,14,15,16,17,18,19,20],
  [21,22,23,24,25,26,27,28,29,30]])

print("dataset.shape: ", dataset.shape)
dataset = np.transpose(dataset)
print(dataset)
print("dataset.shape: ", dataset.shape)

dataset.shape:  (3, 10)
[[ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]
 [10 20 30]]
dataset.shape:  (10, 3)


In [37]:
def split_xy5(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i+time_steps
        y_end_number = x_end_number + y_column

        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i:x_end_number, :]
        tmp_y = dataset[x_end_number:y_end_number,:]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

time_steps = 3
y_column = 1
x, y = split_xy5(dataset, time_steps, y_column)
print('x',"\n",x, "\n", 'y',"\n",y)
print("x.shape: ", x.shape)
print("y.shape: ", y.shape)

x 
 [[[ 1 11 21]
  [ 2 12 22]
  [ 3 13 23]]

 [[ 2 12 22]
  [ 3 13 23]
  [ 4 14 24]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]

 [[ 4 14 24]
  [ 5 15 25]
  [ 6 16 26]]

 [[ 5 15 25]
  [ 6 16 26]
  [ 7 17 27]]

 [[ 6 16 26]
  [ 7 17 27]
  [ 8 18 28]]

 [[ 7 17 27]
  [ 8 18 28]
  [ 9 19 29]]] 
 y 
 [[[ 4 14 24]]

 [[ 5 15 25]]

 [[ 6 16 26]]

 [[ 7 17 27]]

 [[ 8 18 28]]

 [[ 9 19 29]]

 [[10 20 30]]]
x.shape:  (7, 3, 3)
y.shape:  (7, 1, 3)


In [38]:
x = x.reshape(x.shape[0],x.shape[1]*x.shape[2])
print(x.shape)

(7, 9)


In [39]:
# 2. 모델 구성
from keras.models import Sequential
from keras.layers import Dense, LSTM

model = Sequential()
model.add(Dense(64, input_shape=(9,)))
model.add(Dense(3))

# 3. 훈련
model.compile(optimizer='adam',loss='mse')
model.fit(x, y, epochs=300)

Epoch 1/300
1/1 [==============================] - 0s 448ms/step - loss: 361.8447
Epoch 2/300
1/1 [==============================] - 0s 7ms/step - loss: 317.3325
Epoch 3/300
1/1 [==============================] - 0s 7ms/step - loss: 275.9384
Epoch 4/300
1/1 [==============================] - 0s 8ms/step - loss: 237.6936
Epoch 5/300
1/1 [==============================] - 0s 6ms/step - loss: 202.6142
Epoch 6/300
1/1 [==============================] - 0s 8ms/step - loss: 170.7062
Epoch 7/300
1/1 [==============================] - 0s 7ms/step - loss: 141.9610
Epoch 8/300
1/1 [==============================] - 0s 12ms/step - loss: 116.3516
Epoch 9/300
1/1 [==============================] - 0s 8ms/step - loss: 93.8280
Epoch 10/300
1/1 [==============================] - 0s 5ms/step - loss: 74.3149
Epoch 11/300
1/1 [==============================] - 0s 8ms/step - loss: 57.7093
Epoch 12/300
1/1 [==============================] - 0s 5ms/step - loss: 43.8794
Epoch 13/300
1/1 [====================

In [40]:
# 4. 평가, 예측
mse = model.evaluate(x, y)
print("mse: ", mse)

x_pred = np.array([[8,9,10],[18,19,20],[28,29,30]])
x_pred = np.transpose(x_pred)
x_pred = x_pred.reshape(1, x_pred.shape[0]*x_pred.shape[1])
print(x_pred)
print(x_pred.shape)
y_pred = model.predict(x_pred,batch_size=1)
print(y_pred)

1/1 [==============================] - 0s 168ms/step - loss: 4.5038
mse:  4.503814697265625
[[ 8 18 28  9 19 29 10 20 30]]
(1, 9)
1/1 [==============================] - 0s 61ms/step
[[ 7.282605 18.428917 28.767334]]


# 10. RNN 모델(다입력 다:다 세번째)

In [48]:
# 1. 데이터
import numpy as np
dataset = np.array([[1,2,3,4,5,6,7,8,9,10],
 [11,12,13,14,15,16,17,18,19,20],
  [21,22,23,24,25,26,27,28,29,30]])

print("dataset.shape: ", dataset.shape)
dataset = np.transpose(dataset)
print(dataset)
print("dataset.shape: ", dataset.shape)

dataset.shape:  (3, 10)
[[ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]
 [10 20 30]]
dataset.shape:  (10, 3)


In [49]:
def split_xy5(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i+time_steps
        y_end_number = x_end_number + y_column

        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i:x_end_number, :]
        tmp_y = dataset[x_end_number:y_end_number,:]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

time_steps = 3
y_column = 2
x, y = split_xy5(dataset, time_steps, y_column)
print('x',"\n",x, "\n", 'y',"\n",y)
print("x.shape: ", x.shape)
print("y.shape: ", y.shape)

x 
 [[[ 1 11 21]
  [ 2 12 22]
  [ 3 13 23]]

 [[ 2 12 22]
  [ 3 13 23]
  [ 4 14 24]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]

 [[ 4 14 24]
  [ 5 15 25]
  [ 6 16 26]]

 [[ 5 15 25]
  [ 6 16 26]
  [ 7 17 27]]

 [[ 6 16 26]
  [ 7 17 27]
  [ 8 18 28]]] 
 y 
 [[[ 4 14 24]
  [ 5 15 25]]

 [[ 5 15 25]
  [ 6 16 26]]

 [[ 6 16 26]
  [ 7 17 27]]

 [[ 7 17 27]
  [ 8 18 28]]

 [[ 8 18 28]
  [ 9 19 29]]

 [[ 9 19 29]
  [10 20 30]]]
x.shape:  (6, 3, 3)
y.shape:  (6, 2, 3)


In [50]:
y = y.reshape(y.shape[0],y.shape[1]*y.shape[2])
print(y.shape)

(6, 6)


In [51]:
# 2. 모델 구성
from keras.models import Sequential
from keras.layers import Dense, LSTM

model = Sequential()
model.add(LSTM(64, input_shape=(3,3)))
model.add(Dense(6))

# 3. 훈련
model.compile(optimizer='adam',loss='mse')
model.fit(x, y, epochs=300)

Epoch 1/300
1/1 [==============================] - 1s 1s/step - loss: 363.5424
Epoch 2/300
1/1 [==============================] - 0s 7ms/step - loss: 360.9730
Epoch 3/300
1/1 [==============================] - 0s 8ms/step - loss: 358.3884
Epoch 4/300
1/1 [==============================] - 0s 7ms/step - loss: 355.7914
Epoch 5/300
1/1 [==============================] - 0s 6ms/step - loss: 353.1844
Epoch 6/300
1/1 [==============================] - 0s 10ms/step - loss: 350.5691
Epoch 7/300
1/1 [==============================] - 0s 7ms/step - loss: 347.9462
Epoch 8/300
1/1 [==============================] - 0s 6ms/step - loss: 345.3156
Epoch 9/300
1/1 [==============================] - 0s 6ms/step - loss: 342.6760
Epoch 10/300
1/1 [==============================] - 0s 7ms/step - loss: 340.0256
Epoch 11/300
1/1 [==============================] - 0s 9ms/step - loss: 337.3615
Epoch 12/300
1/1 [==============================] - 0s 13ms/step - loss: 334.6805
Epoch 13/300
1/1 [==================

In [52]:
# 4. 평가, 예측
mse = model.evaluate(x, y)
print("mse: ", mse)

x_pred = np.array([[8,9,10],[18,19,20],[28,29,30]])
x_pred = np.transpose(x_pred)
x_pred = x_pred.reshape(1,x_pred.shape[0],x_pred.shape[1])
print(x_pred)
print(x_pred.shape)
y_pred = model.predict(x_pred,batch_size=1)
print(y_pred)

1/1 [==============================] - 0s 491ms/step - loss: 12.5499
mse:  12.549931526184082
[[[ 8 18 28]
  [ 9 19 29]
  [10 20 30]]]
(1, 3, 3)
1/1 [==============================] - 0s 490ms/step
[[ 6.5131717 15.808993  21.407722   7.510415  16.574854  22.015532 ]]


# 11. DNN 모델(다입력 다:다 세번째)

In [53]:
# 1. 데이터
import numpy as np
dataset = np.array([[1,2,3,4,5,6,7,8,9,10],
 [11,12,13,14,15,16,17,18,19,20],
  [21,22,23,24,25,26,27,28,29,30]])

print("dataset.shape: ", dataset.shape)
dataset = np.transpose(dataset)
print(dataset)
print("dataset.shape: ", dataset.shape)

dataset.shape:  (3, 10)
[[ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]
 [10 20 30]]
dataset.shape:  (10, 3)


In [54]:
def split_xy5(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i+time_steps
        y_end_number = x_end_number + y_column

        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i:x_end_number, :]
        tmp_y = dataset[x_end_number:y_end_number,:]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

time_steps = 3
y_column = 2
x, y = split_xy5(dataset, time_steps, y_column)
print('x',"\n",x, "\n", 'y',"\n",y)
print("x.shape: ", x.shape)
print("y.shape: ", y.shape)

x 
 [[[ 1 11 21]
  [ 2 12 22]
  [ 3 13 23]]

 [[ 2 12 22]
  [ 3 13 23]
  [ 4 14 24]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]

 [[ 4 14 24]
  [ 5 15 25]
  [ 6 16 26]]

 [[ 5 15 25]
  [ 6 16 26]
  [ 7 17 27]]

 [[ 6 16 26]
  [ 7 17 27]
  [ 8 18 28]]] 
 y 
 [[[ 4 14 24]
  [ 5 15 25]]

 [[ 5 15 25]
  [ 6 16 26]]

 [[ 6 16 26]
  [ 7 17 27]]

 [[ 7 17 27]
  [ 8 18 28]]

 [[ 8 18 28]
  [ 9 19 29]]

 [[ 9 19 29]
  [10 20 30]]]
x.shape:  (6, 3, 3)
y.shape:  (6, 2, 3)


In [55]:
x = x.reshape(x.shape[0],x.shape[1]*x.shape[2])
print(x.shape)

y = y.reshape(y.shape[0],y.shape[1]*y.shape[2])
print(y.shape)

(6, 9)
(6, 6)


In [57]:
# 2. 모델 구성
from keras.models import Sequential
from keras.layers import Dense, LSTM

model = Sequential()
model.add(Dense(64, input_shape=(9,)))
model.add(Dense(6))

# 3. 훈련
model.compile(optimizer='adam',loss='mse')
model.fit(x, y, epochs=300)

Epoch 1/300
1/1 [==============================] - 0s 317ms/step - loss: 613.1991
Epoch 2/300
1/1 [==============================] - 0s 6ms/step - loss: 570.6069
Epoch 3/300
1/1 [==============================] - 0s 4ms/step - loss: 529.9714
Epoch 4/300
1/1 [==============================] - 0s 5ms/step - loss: 491.2989
Epoch 5/300
1/1 [==============================] - 0s 6ms/step - loss: 454.5850
Epoch 6/300
1/1 [==============================] - 0s 5ms/step - loss: 419.8118
Epoch 7/300
1/1 [==============================] - 0s 4ms/step - loss: 386.9515
Epoch 8/300
1/1 [==============================] - 0s 4ms/step - loss: 355.9679
Epoch 9/300
1/1 [==============================] - 0s 5ms/step - loss: 326.8166
Epoch 10/300
1/1 [==============================] - 0s 4ms/step - loss: 299.4438
Epoch 11/300
1/1 [==============================] - 0s 4ms/step - loss: 273.7863
Epoch 12/300
1/1 [==============================] - 0s 4ms/step - loss: 249.7723
Epoch 13/300
1/1 [=================

In [59]:
# 4. 평가, 예측
mse = model.evaluate(x, y)
print("mse: ", mse)

x_pred = np.array([[8,9,10],[18,19,20],[28,29,30]])
x_pred = np.transpose(x_pred)
x_pred = x_pred.reshape(1,x_pred.shape[0]*x_pred.shape[1])
print(x_pred)
print(x_pred.shape)
y_pred = model.predict(x_pred,batch_size=1)
print(y_pred)

1/1 [==============================] - 0s 27ms/step - loss: 0.2411
mse:  0.24114592373371124
[[ 8 18 28  9 19 29 10 20 30]]
(1, 9)
1/1 [==============================] - 0s 54ms/step
[[10.358483 22.539856 30.962515 11.736736 21.317467 34.410686]]


* ### LSTM이 DNN보다 성능이 안좋게 나온 이유: 하이퍼파라미터 튜닝과 데이터의 크기 때문. 파라미터 튜닝이 잘 안될 경우에는 DNN의 경우 1차 함수(y=wx+b)를 충실히 따르기 때문에 적은 데이터에서는 더 좋은 결과가 나올 수 있음